### ISSUE TITLE
Doesn't seem to insert data when mappings already exist

### ISSUE THREAD

**Issue by mijndert** [awslabs/logstash-output-amazon_es#10]
I have created this config file: https://gist.github.com/mijndert/524209273f654fc992a5
And I have created an index and mappings: https://gist.github.com/mijndert/a5afcb4dd70f45efdee6

When I execute logstash using my config file with the mappings already present, the data seems to just disappear in AWS' ES. The data isn't inserted into the index.

Does anyone know what I'm missing here?

**Comment by magnethy** [comment]
I've noticed the same behavior; any news on this? Did you ever get it to work as expected, @mijndert?

**Comment by mijndert** [comment]
@magnethy No I didn't, still looking for a solution.

**Comment by vukomir** [comment]
HI,

any update on this issue?

**Comment by ninja76** [comment]
I am seeing the same problem.  I am using json_filter and if I create a new index the records get inserted

**Comment by bnewtonius** [comment]
There's a problem with the way it handles errors out of the Elasticsearch client. in amazon_es/http_client it "normalizes" the data creating a hash with 2 keys: "errors", and "statuses". Then it gets returned to amazon_es.rb#submit (line 325), which checks:

`if bulk_response["errors"] && bulk_response["items"]`

It shouldn't normalize the response, but instead just return what it got back from elasticsearch's api. Otherwise good information is stripped out, like the error message and the item that failed.

**Comment by bnewtonius** [comment]
I also had to change the action to "update" and set "doc_as_upsert" to true:

``` 
amazon_es {
        hosts => ["redacted"]
        region => "redacted"
        aws_access_key_id => 'redacted'
        aws_secret_access_key => 'redacted'
        action => "update"
        doc_as_upsert => true
        index => "myindex"
        flush_size => 10
        document_type => "%{[type]}"
        document_id => "%{[@metadata][_id]}"
 }
```

I set type dynamically prior to this, and I use my own id as the document_id. If you don't use your own ID it tends to generate one for you and you end up creating two records when you meant to just update an existing record.

**Comment by AustinTag** [comment]
Closing due to the related pull request having been merged. Please re-open if this problem persists.
